apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SampleApi
  template:
    metadata:
      labels:
        app: SampleApi
    spec:
      containers:
      - name: sampleapirepos
        image: samplecr.azurecr.io/dnrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: sampleapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: SampleApi
